name: CI/CD Pipeline for ejercicio calculadora ampliada - Tema 5

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Debug SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" | awk '{print NR, $0}'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_KEY }}

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_KEY }} 
          HOST: ${{ secrets.REMOTE_HOST }} 
          USERNAME: ${{ secrets.REMOTE_USER }} 
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }} 
        run: |
          mkdir -p ~/.ssh 
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa 
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Crear el directorio de despliegue en el servidor
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH" 

          # Sincronizar archivos
          rsync -avz --delete --exclude 'vendor' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH 

          # Ejecutar Composer en el servidor
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && composer install --no-dev --optimize-autoloader" 

          # Reiniciar Apache
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"
